on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  clippy-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install protobuf-compiler
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            backend
      - name: Check Clippy
        run: cargo clippy --all-features --workspace -- -D warnings
      - name: Check rustfmt
        run: cargo fmt --all -- --check
